f = open("Lec_07\demo.txt","r")
print(f.read())
print(" ")
f = open("Lec_07\demo.txt","r")
print(f.read(5))
print(f.readline())
print(f.readline())
print(" ")
f = open("Lec_07\demo.txt","a")
print(f.write("\nI'll work hard for it Inshallah!"))
f.close()